import Head from 'next/head'
import Navigation from '../components/Navigation'
import Banner from '../components/Banner'
import Restaurants from '../components/Restaurants'
import Aside from '../components/Aside'
import 'bootstrap/dist/css/bootstrap.min.css'

export default function Home() {
  return (
    <div className="col-12 d-flex justify-content-center" >
      <Head>
        <title>imaginamos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" col-11 col-md-10 col-lg-10 col-xl-8 d-flex justify-content-center">
        <div className="row d-flex justify-content-between" >
          <div className="col-sm-12 col-lg-8 " >
            <Navigation/>
             <Banner/>
            <Restaurants/>
          </div>
          <div className="col-sm-11 col-lg-4">
            <Aside/>
          </div>
        </div>
      </main>
    </div>
  )
}
